<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_login.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'cleared' => "Your cookies have been cleared and you are now logged out. Please wait while we redirect you.",
	'login_ok' => "Thankyou for logging in. Please wait while we redirect you.",
	'logout_ok' => "Your cookies have been cleared and you are now logged out. Please wait while we redirect you.",
	'stayloggedin' => "Stay Logged In",
	'thankyou' => "Thankyou for logging in. Please wait while we redirect you to",
)
?>