<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_files.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'addcomment' => "Add Comment",
	'comment_edited' => "Comment Edited",
	'commentadded' => "Thankyou for leaving your comments on this file.",
	'delcomment' => "This comment was successfully removed from the database",
	'deldl' => "Download removed. Press continue to go back",
	'dladded' => "Thankyou for adding this new file to our database.",
	'dlindb' => "Your file has been immediately added to our database.",
	'editcomment' => "Edit Comment",
	'emaillink' => "Email to friend",
	'emailsuccess' => "An email has been successfully sent.",
	'filedl' => "File successfully removed. Please remember to add a new download to this file before exiting",
	'filerated' => "Your rating has been logged. Thankyou for rating this file",
	'filetype' => "File type",
	'friendsemail' => "Friends Email",
	'friendsname' => "Friends Name",
	'invalidemail' => "Your email address is invalid",
	'invalidemail2' => "The recipients email address is invalid",
	'massmove' => "Please select a folder to move the %d selected files to",
	'message' => "Message",
	'movedok' => "Files have been successfully moved",
	'norating' => "No rating",
	'optional' => "Optional",
	'ratefile' => "Rate File",
	'reason' => "You may enter a message below to send to the admin with this error report. Please use it to help us determine the problem by providing as much information as possible",
	'report' => "Report Broken Link",
	'reported' => "The admin has been emailed informing him that this link is broken.",
	'thumbs_added' => "thumbnails successfully uploaded",
	'unknowntype' => "Unknown file type or external URL",
	'youremail' => "Your Email",
	'yourname' => "Your Name",
	'commentsLogIn' => "You must log in before you can add comments",
)
?>