<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_ad_main.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'acp' => "Admin Control Panel",
	'install_exists' => "<b>SECURITY ALERT!</b> - The install directory is still present in your script root directory. This file should be removed to prevent your install being comprimised.",
	'news' => "News",
	'rwdownload' => "RW::Download",
	'stats_mostdl' => "Stats - Most Downloaded",
	'stats_newdls' => "Stats - Latest Downloads",
	'stats_topdls' => "Stats - Top Rated Downloads",
	'upgrade_exists' => "<b>SECURITY ALERT!</b> - The upgrade directory is still present in your script root directory. This is a potential security risk. We HIGHLY reccommend that you remove this file from your server.",
	'nav_checkforup' => "Check for Updates",
)
?>