<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_register.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'adminapp' => "Thankyou for registering. Before you can become a fully registered member, the admin has required that all accounts are manually approved by an admin.",
	'antispam' => "Anti Spam Code",
	'confirmemail' => "Confirm Email",
	'confirmpassword' => "Confirm Password",
	'email' => "Email",
	'emailapp' => "Thankyou for registering. Before you can become a fully registered member, the admin has required that you approve your email address. You will be sent a link shortly asking you to do this. Please click the link in the email to confirm your email address.",
	'invalidkey' => "The specified key is invalid or your email address has already been confirmed.",
	'newuser' => "Thankyou for registering. You can now login and procede to use the site as a fully registered member.",
	'nowvalid' => "You are now a validated member",
	'securitycode' => "Security Code",
	'securitydesc' => "Enter the code from the box above into the box on the right. This is to ensure you are a real person and not a web \"robot\" attempting to spam our database",
	'thankyouconfirm' => "Thankyou for confirming your email address",
)
?>