<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_download.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'invalidreferer' => "LEECH ALERT: We have determined that the website you have come from is directly linking to our files. You are only allowed to download files from our website. Please return to our home page to download this file.",
	'noreferer' => "No refering URL was found. The admin has chosen not to allow downloads from users with no refering urls. This is usually because you are using a firewall that blocks this URL. Disabling or closing your firewall will often solve this problem and allow you to download files.",
)
?>