<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_ad_lang.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'baseskin' => "Base language on",
	'click_download' => "Click to download now",
	'content' => "Content",
	'details_saved' => "Details have been saved",
	'donotmodifyenglish' => "It is not recommended that you delete or translate this language pack. It is the default language pack for RW::Download and all other languages are compared against it to check for untranslated entries. When upgrading any changes made to this file are likely to be lost too.<br>For translating RW::Download we recommend that you first create a new language pack.",
	'edit_details' => "Edit Details",
	'export_complete' => "Language pack exported to /archive_out/",
	'import_successful' => "Import successful",
	'invalid_lang' => "The seleced language pack could not be found",
	'lang_created' => "New language pack created",
	'lang_import' => "Select language to import",
	'langdeleted' => "Language set successfully removed from script",
	'langdelfail' => "Failed to remove language files from server. They may have already been removed or the folder may not have the correct permissions",
	'langname' => "Language Name",
	'langpack' => "Language Pack",
	'langsetmissing' => "Lang set could not be found.",
	'langupdated' => "Language file successfully updated",
	'missing' => "This text has been added to the default English pack but is not in this langage set",
	'no_imports' => "No langauge sets were found in the /archive_in/ folder",
	'no_lang_directory' => "Could not create new language directory. Please make sure that the \"lang\" folder in your script root is set with write permissions [0666/0777]",
	'no_lang_files' => "Unable to save/create language files. Please make sure the following file and all other files in this directory are writable [chmod 0666/0777]",
	'nodatafile' => "Unable to write/create the language data file for exporting this language pack. Please ensure the language directory and all subdirectories are world writeable [0666/0777]",
	'save_changes' => "Save Changes",
	'select_lang' => "Select Language",
	'skin_tag' => "Skin Tag",
	'untranslated' => "This text is untranslated from the default English",
	'languagedir' => "Language direction",
	'characterset' => "Character set (eg. ISO-8859-1)",
	'ltr' => "Left to Right",
	'rtl' => "Right to Left",
	'incompatible_import' => "Sorry but this language pack is not compatible with this version of RW::Download",
	'import' => "Import",
	'visible' => "Visible to users",
)
?>
