<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_ad_logs.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'action' => "Action",
	'log_file' => "File",
	'log_ip' => "IP",
	'log_refer' => "Referer",
	'log_time' => "Time",
	'logsemptied' => "Log file removed",
	'url' => "URL",
	'user' => "User",
)
?>