<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_browse.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'addcomment' => "Add Comment",
	'comment' => "Comment",
	'commentadded' => "Thankyou for leaving your comments on this file.",
	'dateSub' => "Date Submitted",
	'delselect' => "Delete Selected",
	'emailfriend' => "Email a friend",
	'latestdl' => "Latest Download",
	'message' => "Message",
	'moveselect' => "Move Selected",
	'nodl' => "No. of Downloads",
	'nodls' => "No Files in this Category",
	'nofiles' => "No files were found in this category",
	'order' => "Order",
	'report' => "Report Broken Link",
	'select' => "Select",
	'sortdls' => "Sort Downloads by",
	'subcategories' => "Sub-Categories",
)
?>