<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_licence.php
// Language file auto generated by RW::Download 
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array()
?>
