<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_market.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'addedtocart' => "This product has been added to your shopping cart. You can view and edit your cart from the user control panel",
	'addtocart' => "Add to Cart",
	'assign' => "Assign",
	'assign_to_selected' => "Assign to selected",
	'buynow' => "Buy Now",
	'cartItemRemoved' => "The item has been removed from your shopping cart",
	'currency_desc' => "The currency you set as default becomes the currency all product prices are based in. For example, if you chose GBP as default, entering a value of 1.00 as the price of the product means that the product is worth �1.00. If a user chooses to pay in another currency, this value will be multiplied by the rate for that currency shown in the box below.<br>If you choose another default you may want to edit the prices of your products as they may be incorrect. You will also want to change the exchange rate of all other currencies as they will not be correct. We have provided a currency convertor below courtesy of xe.com. Simply select the default currency in the left box and the target currency in the right and click convert.",
	'def_currency' => "Default Currency",
	'dontchange' => "== Don\'t change ==",
	'er_alreadybought' => "You have already bought this product",
	'er_alreadyincart' => "You already have this item in your cart.",
	'er_noPost' => "Tried to validate payment but failed. Post data empty!",
	'er_noitemincart' => "Could not find this item in your cart",
	'er_nomember' => "Could not find a member in the database with that userid",
	'er_nosubcart' => "This is a subscription item. Unfortunately our transaction handling provider does not feature support for adding subscription items to a shopping cart so we can not offer this feature. Please use the Buy Now option for this product.",
	'er_registerToPurchase' => "You must register an account with us to be able to purchase items from our download store",
	'er_testIPN' => "Sorry but you can\'t trick the system by using the sandbox. Nice try though",
	'item_addbandwidth' => "Add this many bytes to users bandwidth limit",
	'item_adddownloads' => "Add this many downloads to users limits",
	'item_autorenew' => "Auto renew subscription",
	'item_customurl' => "Redirect user to this URL after completing payment (optional)",
	'item_downloadlimit' => "Number of downloads allowed for this file",
	'item_expires' => "Expires / Subscription length (Enter 0 or leave blank for no expiry date)",
	'item_name' => "Name",
	'item_newgroup' => "Move user into this group",
	'item_properties' => "Properties",
	'item_subscription' => "Subscription type",
	'item_type' => "Type",
	'item_type_desc' => "Please select the type of product you wish to create. The different types are outlined below:<br><b>Attach to File Product</b> - Create a product and save it so you can assign it to downloads in the database.<br><b>Stand-alone product </b>- Create a standalone product that is not attached to a download. This can be bought by users from their control panel.",
	'item_upgradelevel' => "Upgrade level",
	'item_upgradelevel_desc' => "You can assign more than one product to each download. This specifies the products a user can upgrade to after buying another product on the same download. A higher number equals a higher upgrade level. For example, if a user buys a product from a download with an upgrade level of 2, and there are other products available with levels 1, 3 and 4, the user can upgrade to products with levels 3 or 4. They can not purchase the product with levels 1 or 2",
	'market_price' => "Price",
	'multiple_product' => "Attatch to File",
	'nav_createnew' => "Create new product",
	'nav_editproduct' => "Edit Product",
	'nav_editproducts' => "Edit products",
	'nav_marketplace' => "RW::Marketplace",
	'noHistory' => "We have no record of any past purchases made by you.",
	'noSubscriptions' => "You have no active subscriptions or purchases. If you have previously made some purchases they may have expired. Check your purchase history to view all purchases you have made",
	'noguestsallowed' => "Guests are not allowed to use the marketplace. Please register a free user account before continuing",
	'oneoff' => "One off purchase",
	'price' => "Price",
	'prod_assigned' => "Product assigned to selected downloads.",
	'prodname' => "Product Name",
	'product_added' => "New product successfully added to database",
	'product_updated' => "Product successfully modified",
	'remove' => "Remove",
	'standalone_product' => "Stand-alone",
	'subscription' => "Subscription",
	'usedby' => "Attached to",
	'warn_proddel' => "Are you sure you want to permanantly remove this product? By removing this product you will:<ul><li>Make the product unavailable for purchase from either the user control panel or the download page.<li>If assigned to a download and that download has no other products assigned to it, the file will be available to download for free to any user with permissions to download.<li>Remove any existing subscriptions relating to this ID. All recurring subscriptions will be cancelled, any additional benefits gained from this product will be removed for any user who has purchased it.</ul>",
	'warn_prodlinkdel' => "Are you sure you want to permanantly remove this file from this product? By removing this file you will:<ul><li>Remove the product from this linkd list of purchase options.<li>If the download has no other products assigned to it, the file will be available to download for free to any user with permissions to download.<li>Remove any existing subscriptions relating to this ID. All recurring subscriptions will be cancelled.<li>This will not remove the download itself - just the product assigned to it.</ul>",
	'yourCartIsEmpty' => "Your cart is currently empty. Browse the database and select \"Add to cart\" to add an item to your cart",
	'years' => "Years",
	'months' => "Months",
)
?>
