<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_ad_skins.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'baseskin' => "Base skin on:",
	'changeskin' => "There may be users currently using this skin set. Please select a skin set to switch them to",
	'click_download' => "Click here to download",
	'couldnotread' => "Could not open file for reading, skipping file...",
	'css' => "Cascading Style Sheet",
	'deleteskin' => "Delete Skin",
	'edit_details' => "Edit Details",
	'export_complete' => "Theme was successfully exported to the archive_out folder",
	'from' => "From",
	'globalelements' => "Global Skin Elements",
	'globalskinmissing' => "Global skin element missing or unreadable. Please check that the main.htm and style.css files exist in the following folder:",
	'import_successful' => "Import successful",
	'import' => "Import",
	'invalid_skin' => "The skin set you selected could not be found.",
	'no_imports' => "No skins are currently available for import. Skin archives should be uploaded to the \'archive_in\' folder",
	'no_line_end' => "Could not find any line endings in file, skipping file...",
	'no_skin_dir' => "Could not open directory for reading!",
	'no_skin_files' => "Unable to save/create skin files. Please make sure the following file and all other files in this directory are writable [chmod 0666/0777]",
	'no_skins_directory' => "Could not create new skin directory. Please make sure that the \"skins\" folder in your script root is set with write permissions [0666/0777]",
	'no_template' => "Template set could not be found. Try rebuilding from database.",
	'nodatafile' => "Unable to write/create the skin data file for exporting this skin pack. Please ensure the skin directory and all subdirectories are world writeable [0666/0777]",
	'noskins' => "No skins were found. That is quite a serrious problem",
	'not_a_dir' => "is not a directory, please check the  variable in admin.php.",
	'notwritable' => "The following file is not writable. Please make sure that the directory and the file are writeable [chmod 0777].",
	'rebuild_done' => "Completed database rebuild from PHP cache files.",
	'resync' => "Resyncronise from PHP files",
	'resync_short' => "Resync",
	'save_changes' => "Save Changes",
	'select_lang' => "Select Theme to Export",
	'select_skin' => "Select Skin",
	'setchanged' => "All users using this theme set have been changed to the selected new theme set",
	'skin' => "Theme Pack",
	'skin_created' => "New skin set created",
	'skin_import' => "Available skins",
	'skindeleted' => "Skin successfully deleted",
	'skindelfail' => "Failed to delete directory for this skin from the server. It may have already been deleted",
	'skingsetmissing' => "Skin set could not be found.",
	'skinname' => "Skin Name",
	'skinupdated' => "Skin set successfully edited",
	'switch_skins' => "Change Users Theme Settings",
	'template' => "Global template",
	'to' => "To",
)
?>