<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_usercp.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'approved' => "Approved Files",
	'bandwidth' => "Remaining bandwidth",
	'bandwidth_time' => "Bandwidth time remaining",
	'confirm_email' => "Confirm Email",
	'confirm_password' => "Confirm Password",
	'deldl' => "The download(s) were successfully removed from the database",
	'dlapproved' => "Selected files have been approved",
	'downloaded' => "Downloaded",
	'email' => "Email",
	'filedl' => "File successfully removed. Please remember to add a new download to this file before exiting",
	'files_time' => "Files time remaining",
	'filesremain' => "Files remaining",
	'group' => "Group",
	'home' => "Home",
	'information' => "Information",
	'language' => "Language",
	'limit_reset_off' => "Reset limits is <b>off</b>. When either of your limits reach zero you will not be allowed to download any more files.",
	'limit_reset_on' => "Reset limits is enabled so when the time counters reach zero your allowed file limits will be reset to the default levels for your user group",
	'limits' => "Your Download Limits",
	'limits_desc' => "This section shows the limits the admin has imposed on you for downloading files. The bandwidth limit is the <b>total</b> size allowed for all of your downloads. The file limits show the total number of files you are allowed to download. The times show how long you have before these limits expire or are reset. If <b>either</b> of your limits reaches zero you will not be able to download files",
	'limits_off' => "Download limits are currently disabled and you can download files without any restrictions",
	'profile' => "Profile",
	'receive_email' => "Receive email from administrators",
	'registered' => "Registered on",
	'select' => "Select",
	'settingsSaved' => "Your settings have been saved.",
	'skin' => "Skin",
	'stats' => "Stats",
	'unapproved' => "Unapproved Files",
	'unlimited' => "Unlimited",
	'uploaded' => "Uploaded",
	'your_files' => "Your Files",
)
?>
