<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_warn.php
// Language file auto generated by RW::Download 4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'ext_warn' => "Warning: You are using a non default user database. RW::Download will restrict the options on this page to avoid potential corruption of external database data. Please use the external database\'s admin section to change user details not listed on this page",
	'warn_alreadyrated' => "The file could not be rated as you have already rated this file.",
	'warn_catdel' => "Are you sure you want to delete this category? All downloads in this category will be deleted! This can not be undone",
	'warn_commentdel' => "Are you sure you want to delete this comment from the database? This can not be undone!",
	'warn_copyright' => "Copyright tag removed. You may not remove this tag. RW::Download will not function until this has been added",
	'warn_delcustom' => "Are you sure you want to remove this custom entry? All downloads using this entry will no longer display this value",
	'warn_delfile' => "This will remove the file associated with this download but not the download itself. If you do not replace this file after deleting, the download will effectively be useless. Are you sure you wish to continue?",
	'warn_delmod' => "Are you sure you want to delete this user as a moderator in this category?",
	'warn_dlautomerge' => "Are you sure you want to merge these files in the database? 
<br>The following data will be used from the newest file:
<br> - Author
<br> - Categories
<br> - Description
<br> - File
<br> - Mirrors
<br> - Name
<br> - Price
<br> - Version
<br>
<br>The following data will be used from all files:
<br> - Comments
<br> - Downloadcount
<br> - Thumbnails
<br> - User rating
<br>
<br>The following data will be used from the oldest file:
<br> - Approved yes/no
<br> - Creation date
<br> - Pinned
<br>
<br>The id of the oldest file will be used making sure the download link doesn\'t change.
<br>
<br>DATA NOT USED WILL BE UNRECOVERABLY DELETED",
	'warn_dldel' => "Are you sure you want to delete this link from the database? If this file is in multiple categories those files will also be deleted. This can not be undone!",
	'warn_emptylogs' => "You are about to delete these log files from your database. This can not be undone. A backup will be made and saved to archive_out. If a log archive already exists it will be overwritten. Are you sure you want to continue?",
	'warn_fields' => "The following fields are missing",
	'warn_imgdel' => "Are you sure you want to remove the image from this download? The image will also be removed from the server",
	'warn_missing' => "You did not fill in all the required fields. Please click back",
	'warn_nocatshere' => "You do not have permission to view any categories here. You may need to register and login. If you are already logged in and think you should have access to this area, please contact the administrator.",
	'warn_notloggedin' => "You are not logged in. You must register to access this page.",
	'warn_nouser' => "Could not find a user by that name",
	'warn_report' => "Are you sure you want to report this download as broken?",
	'warn_security' => "SECURITTY ALERT!",
	'warn_unapp' => "This file has not been approved. Only administrators and the owner of this file can see this page until it has been approved by an administrator.",
	'warn_upload' => "Notice: All files will be uploaded when you select \'preview\'. Depending on the size of the files and your internet connection, this could take some time.",
	'warn_useforum' => "You have chosen to use an external database for the user table. You must use the forum you selected to edit members.",
	'warn_langpackmissing' => "Could not find language pack to load: ",
)
?>