<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// lang_ad_files.php
// Language file auto generated by RW::Download
// It is highly recommended you do NOT edit this file
// Doing so could break the language engine and the script
// This language can be edited by using the Language Controls in the Admin CP
$lang = array(
	'plugin_enabled' => "Plugin Enabled",
	'plugin_disabled' => "Plugin Disabled",
	'none' => "None",
	'uninstall' => "Uninstall",
	'nav_plugins' => "Plugins",
)
?>
