<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_portal.php
// Skin file auto generated by RW::Download v4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_portal
{
	function portal_main($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width="100%" border="0" align="center" cellpadding="0" cellspacing="0">
<tr><td width='55%' valign='top'>
<img src='{$rwdInfo->skinurl}/catimages/dlcenter.gif' width='243' height='19'><br><br>
Welcome to the Maidenfans.com download center. In this section of the website you can download a collection of Iron Maiden related tat for your personal computer. We've got a load of cool stuff like fonts, icons, skins for ICQ and more. Click the categories on the right to browse our database. 
<br><br>
If you have something cool that we don't then why not upload it to the site? If it's good we'll approve it so other fans can download it too. You can upload your files by <a href='http://www.maidenfans.com/download/index.php?ACT=useradddl'>clicking here</a>. <br><br>
<img src='{$rwdInfo->skinurl}/catimages/featured.gif' width='210' height='14'><br><br>{$data['featured']}</td><td>{$data['catlist']}
</td></tr></table>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
