<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_usercp.php
// Skin file auto generated by RW::Download v4.0.2
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_usercp
{
	function ucp_editdl($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
{$data['thumbtable']}
{$data['formpost']}
			<table width='100%' border='0' cellspacing='1' cellpadding='3'>
			
				<tr class='mainrow'>
					<td valign='top' width='250'>{$rwdInfo->lang['dlname']}:</td>
					<td valign='top'><input style='width:99%' name='name' type='text' size='30' value='{$data['name']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dldesc']}:</td>
					<td valign='top'><textarea style='width:99%' name='description' cols='24' rows='5'>{$data['description']}</textarea></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['author']}:</td>
					<td valign='top'><input style='width:99%' name='author' type='text' size='30' value='{$data['author']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['thumblimit']}:</td>
					<td valign='top'><input name='thumbs' type='text' size='3' value='{$data['thumbs']}'> <input type='submit' name='updateform' value='{$rwdInfo->lang['updateform']}'></td>
				</tr>
				{$data['thumbrows']}
				{$data['downloadrows']}
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['mirror']}<br>{$rwdInfo->lang['fullurl']}</td>
					<td valign='top'>
						<table width='100%'  border='0 align='center' cellpadding='0' cellspacing='0'>
							<tr>
								<td>{$rwdInfo->lang['mirrorurl']}</td>
								<td>{$rwdInfo->lang['mirrorname']}</td>
							</tr><tr>
								<td><textarea style='width:99%' name='mirrors' cols='24' rows='5'>{$data['mirrors']}</textarea></td>
								<td><textarea style='width:99%' name='mirrornames' cols='24' rows='5'>{$data['mirrornames']}</textarea></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['version']}:</td>
					<td valign='top'><input style='width:99%' name='version' type='text' size='30' value='{$data['version']}'></td>
				</tr>
				{$data['customRows']}
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['cat']}:</td>
					<td valign='top'>{$data['catlistbox']}</td>
				</tr>
				{$data['adminrows']}
			
          <tr class='tablefooter'>
            <td colspan='2'>
			<input type='hidden' name='did' value='{$data['id']}'>
{$data['oldcategory']}
<input type='hidden' name='filesize' value='{$data['filesize']}'>
<input type='hidden' name='realsize' value='{$data['realsize']}'>
<input type='hidden' name='images' value='{$data['thumbs']}'>
<input type='hidden' name='downloads' value='{$data['downloads']}'>
<input type='hidden' name='oldthumb' value='{$data['oldthumb']}'>
<div align='center'><input type='submit' name='preview' value='{$rwdInfo->lang['preview']}'>
<input type='reset' name='reset' value='{$rwdInfo->lang['reset']}'></div>
			</td>
            
          </tr>
  </table></form>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_profile($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<form method='post' enctype='multipart/form-data' action='index.php?ACT=usercp&area=profile'>
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
	<tr class='tableheader'>
		<td colspan='2'>{$rwdInfo->lang['preferences']}</td>
	</tr>
	<tr class='mainrow'>
		<td width='150'>{$rwdInfo->lang['username']}:</td>
		<td>{$data['username']}</td>
	</tr>
RWS;
//startif
		if ($data['showoptions']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
		<td>{$rwdInfo->lang['email']}: </td>
		<td><input type='text' name='email' value='{$data['email']}'></td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['confirm_email']}: </td>
		<td><input type='text' name='email2' value=''></td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['password']}: </td>
		<td><input type='password' name='password' value=''></td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['confirm_password']}: </td>
		<td><input type='password' name='password2' value=''></td>
	</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['language']}: </td>
		<td>{$data['lang']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['skin']}: </td>
		<td>{$data['skin']}</td>
	</tr>
	<tr class='tablefooter'>
		<td colspan='2'><div align='center'><input type='submit' value='{$rwdInfo->lang['submit']}'>
								<input type='reset' value='{$rwdInfo->lang['reset']}'></div></td>
	</tr>
</table>
</form>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_home($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
	<tr class='tableheader'>
		<td colspan='2'>{$rwdInfo->lang['information']}</td>
	</tr>
	<tr class='mainrow'>
		<td width='150'>{$rwdInfo->lang['username']}:</td>
		<td>{$data['username']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['registered']}: </td>
		<td>{$data['registered']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['group']}: </td>
		<td>{$data['group']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['downloaded']}: </td>
		<td>{$data['filesdown']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['uploaded']}: </td>
		<td>{$data['filesup']}</td>
	</tr>
	
	<tr class='tableheader'>
		<td colspan='2'>{$rwdInfo->lang['limits']}</td>
	</tr>
	<tr class='mainrow'>
		<td colspan='2'>{$data['limits_info']}</td>
	</tr>
	<tr class='mainrow'>
		<td width='150'>{$rwdInfo->lang['bandwidth']}:</td>
		<td>{$data['bandwidth']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['bandwidth_time']}: </td>
		<td>{$data['bandwidth_time']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['filesremain']}: </td>
		<td>{$data['files']}</td>
	</tr>
	<tr class='mainrow'>
		<td>{$rwdInfo->lang['files_time']}: </td>
		<td>{$data['files_time']}</td>
	</tr>
</table>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_limits($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='0' cellpadding='0'>
	  <tr>
		<td width='15' class='statHead'>&nbsp;</td>
		<td class='statHead'>{$rwdInfo->lang['limits']}</td>
	  </tr>
	  <tr>
		<td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
		<td class='statRow'>{$data['bandwidth']}</td>
	  </tr>
	  <tr>
		<td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
		<td class='statRow'>{$data['bandwidth_time']}</td>
	  </tr>
	  <tr>
		<td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
		<td class='statRow'>{$data['files']}</td>
	  </tr>
	  <tr>
	  <td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
	  <td class='statRow'>{$data['files_time']}</td>
	  </tr>
	</table><br><br>
	<table width='100%'  border='0' cellspacing='0' cellpadding='0'>
	  <tr>
	  <td width='15' class='statHead'>&nbsp;</td>
	  <td class='statHead'>{$rwdInfo->lang['stats']}</td>
	  </tr>
	  <tr>
	  <td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
	  <td class='statRow'>{$data['filesdown']}</td>
	  </tr>
	  <tr>
	  <td width='15' class='statRow'><div align='center'><img src='{$rwdInfo->skinurl}/images/time.gif'></div></td>
	  <td class='statRow'>{$data['filesup']}</td>
	  </tr>
	</table>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_main($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<div class='tableborder'>
<div id="banner">
	  <img id="leftcap" src="{$rwdInfo->skinurl}/images/headerleft.gif" width="18" height="29">
	  <img id="rightcap" src="{$rwdInfo->skinurl}/images/headerright.gif" width="31" height="29">
	  <div id='catname'>&gt; {$rwdInfo->lang['usercp']}</div>
	</div>
    <table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='4' cellpadding='0'>
					  <tr>
						<td width="200" valign="top">
                        <table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                          <tr class='tableheader'>
                            <td>My Controls </td>
                          </tr>
                          <tr class='mainrow'>
                            <td><a href='index.php?ACT=usercp&area=home'>{$rwdInfo->lang['home']}</a></td>
                          </tr>
                          <tr class='mainrow'>
                            <td><a href='index.php?ACT=usercp&area=profile'>{$rwdInfo->lang['profile']}</a></td>
                          </tr>
                          <tr class='mainrow'>
                            <td><a href='index.php?ACT=usercp&area=files'>{$rwdInfo->lang['approved']}</a></td>
                          </tr>
                          <tr class='mainrow'>
                            <td><a href='index.php?ACT=usercp&area=pending'>{$rwdInfo->lang['unapproved']}</a></td>
                          </tr>
                        </table>
						  {$data['module_nav']}</td>
					    <td valign="top">{$data['ucp_main']}
                        </td>
					  </tr>
                </table>
			</td>
          </tr>
  	</table>
</div>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_listing_foot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='tablefooter'>
RWS;
//startif
		if ($data['canModerate']) {
			$SHTML .= <<<RWS
<td colspan='5'><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
			<tr><td>{$data['pages']}</td><td>
<div align=right>
RWS;
		}//endif
//startif
		if ($data['canModerate'] and $data['displayApprove']) {
			$SHTML .= <<<RWS
<input type='submit' name='approveChecked' value='{$rwdInfo->lang['approve']}'>&nbsp;
RWS;
		}//endif
//startif
		if ($data['canModerate']) {
			$SHTML .= <<<RWS
<input type='submit' name='deleteChecked' value='{$rwdInfo->lang['delete']}'></div></td></tr></table>
</td>
<td width=20><div align='center'><INPUT type='checkbox' id='SelectALL' name='SelectALL' onClick='doselectAll(this)' ></div></td>
RWS;
		}//endif
		else {
			$SHTML .= <<<RWS
<td colspan='4'>{$data['pages']}</td>
RWS;
		}//endelse
		$SHTML .= <<<RWS
          </tr>
</table>
</form>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_listing_head($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<script    >
			function doselectAll(theBox){
			xState=theBox.checked;
			elm=theBox.form.elements;
			for(i=0;i<elm.length;i++)
			 if(elm[i].type=='checkbox')
			   elm[i].checked=xState;
			}
			</script>
<form method='post' enctype='multipart/form-data' action='{$data['form_approve']}'>
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
			  <tr class='tableheader'>
RWS;
//startif
		if ($data['canModerate']) {
			$SHTML .= <<<RWS
<td colspan='6'>
RWS;
		}//endif
		else {
			$SHTML .= <<<RWS
<td colspan='4'>
RWS;
		}//endelse
		$SHTML .= <<<RWS
				{$rwdInfo->lang['your_files']}</td></tr>
              <tr class='tableheader'>
                <td>{$rwdInfo->lang['name']}</td>
                <td><div align='center'>{$rwdInfo->lang['author']}</div></td>
                <td><div align='center'>{$rwdInfo->lang['date']}</div></td>
                <td><div align='center'>{$rwdInfo->lang['downloads']}</div></td>
RWS;
//startif
		if ($data['canModerate']) {
			$SHTML .= <<<RWS
<td><div align='center'>{$rwdInfo->lang['edit']}</div></td>
				<td><div align='center'>{$rwdInfo->lang['select']}</div></td>
RWS;
		}//endif
		$SHTML .= <<<RWS
		</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_listing_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td>{$data['name']} {$data['pinned']} {$data['new']} {$data['updated']}</td>
                  <td><div align='center'>{$data['author']}</div></td>
                  <td><div align='center'>{$data['date']}</div></td>
				  <td><div align='center'>{$data['downloads']}</div></td>
RWS;
//startif
		if ($data['canModerate']) {
			$SHTML .= <<<RWS
<td><div align='center'>[ {$data['edit']} ]</div></td>
				  <td><div align='center'><input type='checkbox' name='dlid[]' value='{$data['editvalue']}'></div></td>
RWS;
		}//endif
		$SHTML .= <<<RWS
			  </tr>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
