<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_market.php
// Skin file auto generated by RW::Download v4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_market
{
	function product_price_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['market_price']} {$data['defcurrency_name']}:</td>
					<td valign='top'><input name='price' type='text' style='width:100%' value='{$data['price']}'></td>
				</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_nav($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                            <tr class='tableheader'>
                              <td>RW::Marketplace</td>
                            </tr>
RWS;
//startif
		if ($data['allowcredits']) {
			$SHTML .= <<<RWS
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=market&area=credit'>Purchase Credits</a></td>
                            </tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=market&area=products'>Standalone Products</a></td>
                            </tr>
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=market&area=mycart'>My Cart</a></td>
                            </tr>
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=market&area=mysubs'>My Current Subscriptions</a></td>
                            </tr>
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=market&area=history'>Purchase History</a></td>
                            </tr>
                          </table>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_profile($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
	<tr class='mainrow'>
		<td width='150'>{$rwdInfo->lang['def_currency']}:</td>
		<td>{$data['currency']}</td>
	</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mysubshead($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                          <tr class='acptablesubhead'>
                            <td>Product</td>
                            <td>Previous Group</td>
                            <td>Expires</td>
                            <td>Downloads Remaining</td>
                            <td>Subscription Status</td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mysubsrow($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
                            <td width='150'>{$data['product']}</td>
                            <td>{$data['prevgroup']}</td>
                            <td>{$data['expires']}</td>
                            <td>{$data['files']}</td>
                            <td>{$data['substatus']}</td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mysubsfoot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_productshead($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                          <tr class='tableheader'>
                            <td width='150'>Product</td>
                            <td>Subscription Length</td>
                            <td>Price</td>
                            <td>Additional Downloads</td>
                            <td>Additional Bandwidth</td>
                            <td>Usergroup Promotion</td>
                            <td width='100'>Purchase</td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_productsrow($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
                            <td>{$data['product']}</td>
                            <td>{$data['length']}</td>
                            <td>{$data['price']}</td>
                            <td>{$data['downloads']}</td>
                            <td>{$data['bandwidth']}</td>
                            <td>{$data['group']}</td>
                            <td><a href='index.php?ACT=market&area=buynow&buynow=1&prodid={$data['prodid']}&sa=1'>Buy Now</a> | <a href='index.php?ACT=market&area=addtocart&prodid={$data['prodid']}'>Add to Cart</a></td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_productsfoot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mycarthead($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                          <tr class='tableheader'>
                            <td>Product</td>
                            <td width='100'>Remove</td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mycartrow($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
                            <td width='150'>{$data['product']}</td>
                            <td><a href='index.php?ACT=market&area=removeitem&cid={$data['cid']}'>{$rwdInfo->lang['remove']}</a></td>
                          </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function ucp_mycartfoot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table><form method='post' enctype='multipart/form-data' action='index.php?ACT=market&area=checkout'>
<input type='submit' name='buycart' value='Checkout Now'></form>
RWS;
//--END--//
		return $SHTML;
	}

	function acp_currencyConvert($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<!-- XE.com Universal Currency Converter(tm) Input Page Starts -->
<!-- Copyright (c) 2005 XE.com. Unauthorized use prohibited. -->
<!-- Input Template Version 3.10 -->
<!-- You may reformat this page section, but do not delete lines or variables that start with an asterisk -->

<FORM METHOD=POST ACTION="http://www.xe.com/ucc/convert.cgi" target='_blank'>

<P><TABLE WIDTH=100% CELLPADDING=1 CELLSPACING=0 BORDER=0  BGCOLOR=#000000><TR><TD ALIGN=CENTER>
<TABLE WIDTH=100% CELLPADDING=3 CELLSPACING=1 BORDER=0>

<TR VALIGN=TOP ALIGN=CENTER>
  <TD BGCOLOR=#FFF090><B>
    <FONT FACE="Arial,Helvetica">
    <FONT SIZE=+1>xe.com&nbsp;</FONT>
    Universal Currency Converter<FONT SIZE=-1><SUP> &reg;</SUP></FONT>
    </FONT>
  </B></TD>
</TR>

<TR VALIGN=TOP ALIGN=LEFT>
  <TD VALIGN=MIDDLE ALIGN=CENTER BGCOLOR=#FFFFFF>
  <TABLE CELLSPACING=3 CELLPADDING=2 BORDER=0 WIDTH=100%><TR>
  <TD><FONT FACE="Arial,Helvetica">
    <!XERC-UCC1-P1.1-R1>
    <B>Convert this amount</B><BR>
  </FONT></TD>
  <TD><FONT FACE="Arial,Helvetica">
    <!XERC-UCC1-P1.3-R1>
    <B>of this type of currency</B><BR>
  </FONT></TD>
  <TD><FONT FACE="Arial,Helvetica">
    <!XERC-UCC1-P1.5-R1>
    <B>into this type of currency.</B><BR>
  </FONT></TD>
</TR>

<TR VALIGN=TOP ALIGN=LEFT>

  <TD><FONT FACE="Arial,Helvetica">
    <INPUT TYPE="text" NAME="Amount" VALUE="1" SIZE=10><BR>
    <!XERC-UCC1-P1.2-R2>
    <FONT SIZE=-1><B>enter any amount</B></FONT>
  </FONT></TD>

  <TD><FONT FACE="Arial,Helvetica" SIZE=-1>
    <SELECT NAME="From" SIZE=5>
      <OPTION VALUE="EUR" SELECTED>Euro EUR</OPTION>
      <OPTION VALUE="USD">United States Dollars USD</OPTION>
      <OPTION VALUE="GBP">United Kingdom Pounds GBP</OPTION>
      <OPTION VALUE="CAD">Canada Dollars CAD</OPTION>
      <OPTION VALUE="AUD">Australia Dollars AUD</OPTION>
      <OPTION VALUE="JPY">Japan Yen JPY</OPTION>
      <OPTION VALUE="INR">India Rupees INR</OPTION>
      <OPTION VALUE="NZD">New Zealand Dollars NZD</OPTION>
      <OPTION VALUE="CHF">Switzerland Francs CHF</OPTION>
      <OPTION VALUE="ZAR">South Africa Rand ZAR</OPTION>
      <OPTION VALUE="EUR">-- Top 85 Currencies: --</OPTION>
      <OPTION VALUE="AFA">Afghanistan Afghanis AFA</option>
      <OPTION VALUE="ALL">Albania Leke ALL</option>
      <OPTION VALUE="DZD">Algeria Dinars DZD</OPTION>
      <OPTION VALUE="USD">America (United States) Dollars USD</OPTION>
      <OPTION VALUE="ARS">Argentina Pesos ARS</OPTION>
      <OPTION VALUE="AUD">Australia Dollars AUD</OPTION>
      <OPTION VALUE="ATS">Austria Schillings ATS*</OPTION>
      <OPTION VALUE="BSD">Bahamas Dollars BSD</OPTION>
      <OPTION VALUE="BHD">Bahrain Dinars BHD</OPTION>
      <OPTION VALUE="BDT">Bangladesh Taka BDT</OPTION>
      <OPTION VALUE="BBD">Barbados Dollars BBD</OPTION>
      <OPTION VALUE="BEF">Belgium Francs BEF*</OPTION>
      <OPTION VALUE="BMD">Bermuda Dollars BMD</OPTION>
      <OPTION VALUE="BRL">Brazil Reais BRL</OPTION>
      <OPTION VALUE="BGN">Bulgaria Leva BGN</OPTION>
      <OPTION VALUE="CAD">Canada Dollars CAD</OPTION>
      <OPTION VALUE="XOF">CFA BCEAO Francs XOF</OPTION>
      <OPTION VALUE="XAF">CFA BEAC Francs XAF</OPTION>
      <OPTION VALUE="CLP">Chile Pesos CLP</OPTION>
      <OPTION VALUE="CNY">China Yuan Renminbi CNY</OPTION>
      <OPTION VALUE="COP">Colombia Pesos COP</OPTION>
      <OPTION VALUE="XPF">Comptoirs Fran�ais du Pacifique Francs</OPTION>
      <OPTION VALUE="CRC">Costa Rica Colones CRC</OPTION>
      <OPTION VALUE="HRK">Croatia Kuna HRK</OPTION>
      <OPTION VALUE="CYP">Cyprus Pounds CYP</OPTION>
      <OPTION VALUE="CZK">Czech Republic Koruny CZK</OPTION>
      <OPTION VALUE="DKK">Denmark Kroner DKK</OPTION>
      <OPTION VALUE="DEM">Deutsche (Germany) Marks DEM*</OPTION>
      <OPTION VALUE="DOP">Dominican Republic Pesos DOP</OPTION>
      <OPTION VALUE="NLG">Dutch (Netherlands) Guilders NLG*</OPTION>
      <OPTION VALUE="XCD">Eastern Caribbean Dollars XCD</OPTION>
      <OPTION VALUE="EGP">Egypt Pounds EGP</OPTION>
      <OPTION VALUE="EEK">Estonia Krooni EEK</OPTION>
      <OPTION VALUE="EUR">Euro EUR</OPTION>
      <OPTION VALUE="FJD">Fiji Dollars FJD</OPTION>
      <OPTION VALUE="FIM">Finland Markkaa FIM*</OPTION>
      <OPTION VALUE="FRF">France Francs FRF*</OPTION>
      <OPTION VALUE="DEM">Germany Deutsche Marks DEM*</OPTION>
      <OPTION VALUE="XAU">Gold Ounces XAU</OPTION>
      <OPTION VALUE="GRD">Greece Drachmae GRD*</OPTION>
      <OPTION VALUE="NLG">Holland (Netherlands) Guilders NLG*</OPTION>
      <OPTION VALUE="HKD">Hong Kong Dollars HKD</OPTION>
      <OPTION VALUE="HUF">Hungary Forint HUF</OPTION>
      <OPTION VALUE="ISK">Iceland Kronur ISK</OPTION>
      <OPTION VALUE="XDR">IMF Special Drawing Right XDR</OPTION>
      <OPTION VALUE="INR">India Rupees INR</OPTION>
      <OPTION VALUE="IDR">Indonesia Rupiahs IDR</OPTION>
      <OPTION VALUE="IRR">Iran Rials IRR</OPTION>
      <OPTION VALUE="IQD">Iraq Dinars IQD</OPTION>
      <OPTION VALUE="IEP">Ireland Pounds IEP*</OPTION>
      <OPTION VALUE="ILS">Israel New Shekels ILS</OPTION>
      <OPTION VALUE="ITL">Italy Lire ITL*</OPTION>
      <OPTION VALUE="JMD">Jamaica Dollars JMD</OPTION>
      <OPTION VALUE="JPY">Japan Yen JPY</OPTION>
      <OPTION VALUE="JOD">Jordan Dinars JOD</OPTION>
      <OPTION VALUE="KES">Kenya Shillings KES</OPTION>
      <OPTION VALUE="KRW">Korea (South) Won KRW</OPTION>
      <OPTION VALUE="KWD">Kuwait Dinars KWD</OPTION>
      <OPTION VALUE="LBP">Lebanon Pounds LBP</OPTION>
      <OPTION VALUE="LUF">Luxembourg Francs LUF*</OPTION>
      <OPTION VALUE="MYR">Malaysia Ringgits MYR</OPTION>
      <OPTION VALUE="MTL">Malta Liri MTL</OPTION>
      <OPTION VALUE="MUR">Mauritius Rupees MUR</OPTION>
      <OPTION VALUE="MXN">Mexico Pesos MXN</OPTION>
      <OPTION VALUE="MAD">Morocco Dirhams MAD</OPTION>
      <OPTION VALUE="NLG">Netherlands Guilders NLG*</OPTION>
      <OPTION VALUE="NZD">New Zealand Dollars NZD</OPTION>
      <OPTION VALUE="NOK">Norway Kroner NOK</OPTION>
      <OPTION VALUE="OMR">Oman Rials OMR</OPTION>
      <OPTION VALUE="PKR">Pakistan Rupees PKR</OPTION>
      <OPTION VALUE="XPD">Palladium Ounces XPD</OPTION>
      <OPTION VALUE="PEN">Peru Nuevos Soles PEN</OPTION>
      <OPTION VALUE="PHP">Philippines Pesos PHP</OPTION>
      <OPTION VALUE="XPT">Platinum Ounces XPT</OPTION>
      <OPTION VALUE="PLN">Poland Zlotych PLN</OPTION>
      <OPTION VALUE="PTE">Portugal Escudos PTE*</OPTION>
      <OPTION VALUE="QAR">Qatar Riyals QAR</OPTION>
      <OPTION VALUE="ROL">Romania Lei ROL</OPTION>
      <OPTION VALUE="RUB">Russia Rubles RUB</OPTION>
      <OPTION VALUE="SAR">Saudi Arabia Riyals SAR</OPTION>
      <OPTION VALUE="XAG">Silver Ounces XAG</OPTION>
      <OPTION VALUE="SGD">Singapore Dollars SGD</OPTION>
      <OPTION VALUE="SKK">Slovakia Koruny SKK</OPTION>
      <OPTION VALUE="SIT">Slovenia Tolars SIT</OPTION>
      <OPTION VALUE="ZAR">South Africa Rand ZAR</OPTION>
      <OPTION VALUE="KRW">South Korea Won KRW</OPTION>
      <OPTION VALUE="ESP">Spain Pesetas ESP*</OPTION>
      <OPTION VALUE="XDR">Special Drawing Rights (IMF) XDR</OPTION>
      <OPTION VALUE="LKR">Sri Lanka Rupees LKR</OPTION>
      <OPTION VALUE="SDD">Sudan Dinars SDD</OPTION>
      <OPTION VALUE="SEK">Sweden Kronor SEK</OPTION>
      <OPTION VALUE="CHF">Switzerland Francs CHF</OPTION>
      <OPTION VALUE="TWD">Taiwan New Dollars TWD</OPTION>
      <OPTION VALUE="THB">Thailand Baht THB</OPTION>
      <OPTION VALUE="TTD">Trinidad and Tobago Dollars TTD</OPTION>
      <OPTION VALUE="TND">Tunisia Dinars TND</OPTION>
      <OPTION VALUE="TRY">Turkey New Lira TRY</OPTION>
      <OPTION VALUE="TRL">Turkey Lira TRL*</OPTION>
      <OPTION VALUE="AED">United Arab Emirates Dirhams AED</OPTION>
      <OPTION VALUE="GBP">United Kingdom Pounds GBP</OPTION>
      <OPTION VALUE="USD">United States Dollars USD</OPTION>
      <OPTION VALUE="VEB">Venezuela Bolivares VEB</OPTION>
      <OPTION VALUE="VND">Vietnam Dong VND</OPTION>
      <OPTION VALUE="ZMK">Zambia Kwacha ZMK</OPTION>
      <OPTION VALUE="EUR">-- Special Units: --</OPTION>
      <OPTION VALUE="XAF">CFA BEAC Francs XAF</OPTION>
      <OPTION VALUE="XOF">CFA BCEAO Francs XOF</OPTION>
      <OPTION VALUE="XPF">Comptoirs Fran�ais du Pacifique Francs</OPTION>
      <OPTION VALUE="XCD">Eastern Caribbean Dollars XCD</OPTION>
      <OPTION VALUE="EUR">Euro EUR</OPTION>
      <OPTION VALUE="XDR">IMF Special Drawing Rights XDR</OPTION>
      <OPTION VALUE="XAU">-- Precious Metals: --</OPTION>
      <OPTION VALUE="XAG">Silver Ounces XDR</OPTION>
      <OPTION VALUE="XAU">Gold Ounces XAU</OPTION>
      <OPTION VALUE="XPT">Platinum Ounces XPT</OPTION>
      <OPTION VALUE="XPD">Palladium Ounces XPD</OPTION>
    </SELECT><BR>
    <!XERC-UCC1-P1.4-R2>
    <FONT SIZE=-1><B>scroll down to see more currencies</B></FONT>
  </FONT></TD>

  <TD><FONT FACE="Arial,Helvetica" SIZE=-1>
    <SELECT NAME="To" SIZE=5>
      <OPTION VALUE="USD" SELECTED>United States Dollars USD</OPTION>
      <OPTION VALUE="EUR">Euro EUR</OPTION>
      <OPTION VALUE="GBP">United Kingdom Pounds GBP</OPTION>
      <OPTION VALUE="CAD">Canada Dollars CAD</OPTION>
      <OPTION VALUE="AUD">Australia Dollars AUD</OPTION>
      <OPTION VALUE="JPY">Japan Yen JPY</OPTION>
      <OPTION VALUE="INR">India Rupees INR</OPTION>
      <OPTION VALUE="NZD">New Zealand Dollars NZD</OPTION>
      <OPTION VALUE="CHF">Switzerland Francs CHF</OPTION>
      <OPTION VALUE="ZAR">South Africa Rand ZAR</OPTION>
      <OPTION VALUE="USD">-- Top 85 Currencies: --</OPTION>
      <OPTION VALUE="AFA">Afghanistan Afghanis AFA</option>
      <OPTION VALUE="ALL">Albania Leke ALL</option>
      <OPTION VALUE="DZD">Algeria Dinars DZD</OPTION>
      <OPTION VALUE="USD">America (United States) Dollars USD</OPTION>
      <OPTION VALUE="ARS">Argentina Pesos ARS</OPTION>
      <OPTION VALUE="AUD">Australia Dollars AUD</OPTION>
      <OPTION VALUE="ATS">Austria Schillings ATS*</OPTION>
      <OPTION VALUE="BSD">Bahamas Dollars BSD</OPTION>
      <OPTION VALUE="BHD">Bahrain Dinars BHD</OPTION>
      <OPTION VALUE="BDT">Bangladesh Taka BDT</OPTION>
      <OPTION VALUE="BBD">Barbados Dollars BBD</OPTION>
      <OPTION VALUE="BEF">Belgium Francs BEF*</OPTION>
      <OPTION VALUE="BMD">Bermuda Dollars BMD</OPTION>
      <OPTION VALUE="BRL">Brazil Reais BRL</OPTION>
      <OPTION VALUE="BGN">Bulgaria Leva BGN</OPTION>
      <OPTION VALUE="CAD">Canada Dollars CAD</OPTION>
      <OPTION VALUE="XOF">CFA BCEAO Francs XOF</OPTION>
      <OPTION VALUE="XAF">CFA BEAC Francs XAF</OPTION>
      <OPTION VALUE="CLP">Chile Pesos CLP</OPTION>
      <OPTION VALUE="CNY">China Yuan Renminbi CNY</OPTION>
      <OPTION VALUE="COP">Colombia Pesos COP</OPTION>
      <OPTION VALUE="XPF">Comptoirs Fran�ais du Pacifique Francs</OPTION>
      <OPTION VALUE="CRC">Costa Rica Colones CRC</OPTION>
      <OPTION VALUE="HRK">Croatia Kuna HRK</OPTION>
      <OPTION VALUE="CYP">Cyprus Pounds CYP</OPTION>
      <OPTION VALUE="CZK">Czech Republic Koruny CZK</OPTION>
      <OPTION VALUE="DKK">Denmark Kroner DKK</OPTION>
      <OPTION VALUE="DEM">Deutsche (Germany) Marks DEM*</OPTION>
      <OPTION VALUE="DOP">Dominican Republic Pesos DOP</OPTION>
      <OPTION VALUE="NLG">Dutch (Netherlands) Guilders NLG*</OPTION>
      <OPTION VALUE="XCD">Eastern Caribbean Dollars XCD</OPTION>
      <OPTION VALUE="EGP">Egypt Pounds EGP</OPTION>
      <OPTION VALUE="EEK">Estonia Krooni EEK</OPTION>
      <OPTION VALUE="EUR">Euro EUR</OPTION>
      <OPTION VALUE="FJD">Fiji Dollars FJD</OPTION>
      <OPTION VALUE="FIM">Finland Markkaa FIM*</OPTION>
      <OPTION VALUE="FRF">France Francs FRF*</OPTION>
      <OPTION VALUE="DEM">Germany Deutsche Marks DEM*</OPTION>
      <OPTION VALUE="XAU">Gold Ounces XAU</OPTION>
      <OPTION VALUE="GRD">Greece Drachmae GRD*</OPTION>
      <OPTION VALUE="NLG">Holland (Netherlands) Guilders NLG*</OPTION>
      <OPTION VALUE="HKD">Hong Kong Dollars HKD</OPTION>
      <OPTION VALUE="HUF">Hungary Forint HUF</OPTION>
      <OPTION VALUE="ISK">Iceland Kronur ISK</OPTION>
      <OPTION VALUE="XDR">IMF Special Drawing Right XDR</OPTION>
      <OPTION VALUE="INR">India Rupees INR</OPTION>
      <OPTION VALUE="IDR">Indonesia Rupiahs IDR</OPTION>
      <OPTION VALUE="IRR">Iran Rials IRR</OPTION>
      <OPTION VALUE="IQD">Iraq Dinars IQD</OPTION>
      <OPTION VALUE="IEP">Ireland Pounds IEP*</OPTION>
      <OPTION VALUE="ILS">Israel New Shekels ILS</OPTION>
      <OPTION VALUE="ITL">Italy Lire ITL*</OPTION>
      <OPTION VALUE="JMD">Jamaica Dollars JMD</OPTION>
      <OPTION VALUE="JPY">Japan Yen JPY</OPTION>
      <OPTION VALUE="JOD">Jordan Dinars JOD</OPTION>
      <OPTION VALUE="KES">Kenya Shillings KES</OPTION>
      <OPTION VALUE="KRW">Korea (South) Won KRW</OPTION>
      <OPTION VALUE="KWD">Kuwait Dinars KWD</OPTION>
      <OPTION VALUE="LBP">Lebanon Pounds LBP</OPTION>
      <OPTION VALUE="LUF">Luxembourg Francs LUF*</OPTION>
      <OPTION VALUE="MYR">Malaysia Ringgits MYR</OPTION>
      <OPTION VALUE="MTL">Malta Liri MTL</OPTION>
      <OPTION VALUE="MUR">Mauritius Rupees MUR</OPTION>
      <OPTION VALUE="MXN">Mexico Pesos MXN</OPTION>
      <OPTION VALUE="MAD">Morocco Dirhams MAD</OPTION>
      <OPTION VALUE="NLG">Netherlands Guilders NLG*</OPTION>
      <OPTION VALUE="NZD">New Zealand Dollars NZD</OPTION>
      <OPTION VALUE="NOK">Norway Kroner NOK</OPTION>
      <OPTION VALUE="OMR">Oman Rials OMR</OPTION>
      <OPTION VALUE="PKR">Pakistan Rupees PKR</OPTION>
      <OPTION VALUE="XPD">Palladium Ounces XPD</OPTION>
      <OPTION VALUE="PEN">Peru Nuevos Soles PEN</OPTION>
      <OPTION VALUE="PHP">Philippines Pesos PHP</OPTION>
      <OPTION VALUE="XPT">Platinum Ounces XPT</OPTION>
      <OPTION VALUE="PLN">Poland Zlotych PLN</OPTION>
      <OPTION VALUE="PTE">Portugal Escudos PTE*</OPTION>
      <OPTION VALUE="QAR">Qatar Riyals QAR</OPTION>
      <OPTION VALUE="ROL">Romania Lei ROL</OPTION>
      <OPTION VALUE="RUB">Russia Rubles RUB</OPTION>
      <OPTION VALUE="SAR">Saudi Arabia Riyals SAR</OPTION>
      <OPTION VALUE="XAG">Silver Ounces XAG</OPTION>
      <OPTION VALUE="SGD">Singapore Dollars SGD</OPTION>
      <OPTION VALUE="SKK">Slovakia Koruny SKK</OPTION>
      <OPTION VALUE="SIT">Slovenia Tolars SIT</OPTION>
      <OPTION VALUE="ZAR">South Africa Rand ZAR</OPTION>
      <OPTION VALUE="KRW">South Korea Won KRW</OPTION>
      <OPTION VALUE="ESP">Spain Pesetas ESP*</OPTION>
      <OPTION VALUE="XDR">Special Drawing Rights (IMF) XDR</OPTION>
      <OPTION VALUE="LKR">Sri Lanka Rupees LKR</OPTION>
      <OPTION VALUE="SDD">Sudan Dinars SDD</OPTION>
      <OPTION VALUE="SEK">Sweden Kronor SEK</OPTION>
      <OPTION VALUE="CHF">Switzerland Francs CHF</OPTION>
      <OPTION VALUE="TWD">Taiwan New Dollars TWD</OPTION>
      <OPTION VALUE="THB">Thailand Baht THB</OPTION>
      <OPTION VALUE="TTD">Trinidad and Tobago Dollars TTD</OPTION>
      <OPTION VALUE="TND">Tunisia Dinars TND</OPTION>
      <OPTION VALUE="TRY">Turkey New Lira TRY</OPTION>
      <OPTION VALUE="TRL">Turkey Lira TRL*</OPTION>
      <OPTION VALUE="AED">United Arab Emirates Dirhams AED</OPTION>
      <OPTION VALUE="GBP">United Kingdom Pounds GBP</OPTION>
      <OPTION VALUE="USD">United States Dollars USD</OPTION>
      <OPTION VALUE="VEB">Venezuela Bolivares VEB</OPTION>
      <OPTION VALUE="VND">Vietnam Dong VND</OPTION>
      <OPTION VALUE="ZMK">Zambia Kwacha ZMK</OPTION>
      <OPTION VALUE="EUR">-- Special Units: --</OPTION>
      <OPTION VALUE="XAF">CFA BEAC Francs XAF</OPTION>
      <OPTION VALUE="XOF">CFA BCEAO Francs XOF</OPTION>
      <OPTION VALUE="XPF">Comptoirs Fran�ais du Pacifique Francs</OPTION>
      <OPTION VALUE="XCD">Eastern Caribbean Dollars XCD</OPTION>
      <OPTION VALUE="EUR">Euro EUR</OPTION>
      <OPTION VALUE="XDR">IMF Special Drawing Rights XDR</OPTION>
      <OPTION VALUE="XAU">-- Precious Metals: --</OPTION>
      <OPTION VALUE="XAG">Silver Ounces XDR</OPTION>
      <OPTION VALUE="XAU">Gold Ounces XAU</OPTION>
      <OPTION VALUE="XPT">Platinum Ounces XPT</OPTION>
      <OPTION VALUE="XPD">Palladium Ounces XPD</OPTION>
    </SELECT><BR>
    <!XERC-UCC1-P1.6-R2>
    <FONT SIZE=-1><B>scroll down to see more currencies</B></FONT>
  </FONT></TD>

</TR>

<TR ALIGN=CENTER>
  <TD COLSPAN=3 ALIGN=CENTER><FONT FACE="Arial,Helvetica,sans-serif">
    <!XERC-UCC1-P3.2-R1>
    <INPUT VALUE="Click Here to Perform Currency Conversion" type=submit>
  </FONT></TD>
</TR>
</TD></TR></TABLE>

<TR ALIGN=CENTER>
  <TD BGCOLOR=#F0F0F0 ALIGN=CENTER><FONT FACE="Arial,Helvetica,sans-serif" SIZE=-1 COLOR=#808080>
    <!-- Important Section Start -->
    <!-- ALL of the contents of this section are required under the usage agreement! -->
    <FONT COLOR=#808080><B>Universal Currency Converter</B> under license from <B>XE.com</B>. <A HREF="http://www.xe.com/legal/" style="color:#808080;">Terms of Use</A>
    <!-- Important Section Ends -->
  </FONT></TD>
</TR>

</TABLE>
</TD></TR></TABLE></P>

<!-- XE.com Universal Currency Converter(tm) Input Page Ends -->

RWS;
//--END--//
		return $SHTML;
	}

	function ad_cat_head()
	{
		global $rwdInfo;
		$SHTML = "<table width='100%' border='0' cellspacing='2' cellpadding='2'>
			  <tr class='acptablesubhead'>
			    <td>Category</td>
			    <td width='50'><div align='center'>Downloads</div></td>
			  </tr>";
		return $SHTML;
	}

	function ad_cat_foot()
	{
		global $rwdInfo;
		$SHTML = "</table>";
		return $SHTML;
	}

	function ad_cat_row($data)
	{
		global $rwdInfo;
		$SHTML = "<tr class='normalrow'>
    <td valign=top><b>{$data['cat_name']}</b></td>
	<td valign=top><div align='center'>
        {$data['cat_dlcount']}</div></td>
	<tr class=normalrow>
	<td colspan=4>{$data['cat_desc']}</td>

  </tr>";
		return $SHTML;
	}

	function ad_cat_listing_head($data)
	{
		global $rwdInfo;
		$SHTML = "{$data['pages']}
			<form method='post' action='{$data['assignpost']}'>
			<table width='100%' border='0' cellspacing='2' cellpadding='2'>
			<tr class='acptablesubhead'>
			<td colspan=4>{$data['cat_name']}</td>
			</tr><tr class='acptablesubhead'>
			<td width=30>&nbsp;</td>
			<td width=150>Name</td>
			<td width=75>Author</td>
			<td width=75>Date</td>
			</tr>";
		return $SHTML;
	}

	function ad_cat_listing_foot($data)
	{
		global $rwdInfo;
		$SHTML = "<tr class='acptablesubhead'>

		<td colspan=2>{$data['pages']}</td>
		<td colspan=2><div align='right'>
		<input type='hidden' name='id' value='{$data['id']}'>
		<input type='submit' name='assign' value='{$rwdInfo->lang['assign_to_selected']}'>
		</div></td>
		</tr>
		</table>
		</form>";
		return $SHTML;
	}

	function ad_cat_listing_row($data)
	{
		global $rwdInfo;
		$SHTML = "<tr class='normalrow'>
				<td><input type='checkbox' name='dlid[]' value='{$data['id']}'></td>
				<td><b>{$data['name']} {$data['new']} {$data['updated']}</b></td>
				<td>{$data['author']}</td>
				<td>{$data['date']}</td>
			  </tr>";
		return $SHTML;
	}
}

?>
