<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_licence.php
// Skin file auto generated by RW::Download v4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_licence
{
	function ucp_nav($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                            <tr class='tableheader'>
                              <td>My Licences</td>
                            </tr>
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=licence&area=generate'>Generate Licence</a></td>
                            </tr>
                          </table>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
