<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_licence.php
// Skin file auto generated by RW::Download v4.1
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_licence
{
	function ucp_nav($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
                            <tr class='tableheader'>
                              <td>My Licences</td>
                            </tr>
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=licence&area=viewall'>View Licences</a></td>
                            </tr>
RWS;
//startif
		if ($data['isAdmin']) {
			$SHTML .= <<<RWS
                            <tr class='mainrow'>
                              <td><a href='index.php?ACT=licence&area=getsite'>Licenced Site Search</a></td>
                            </tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
                          </table>
RWS;
//--END--//
		return $SHTML;
	}

	function licence_head($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
You can only generate one licence at a time (to avoid people generating, installing and regenerating). If you need to re-generate your licence because you have changed domain names then please contact us at <a href='&#109;&#97;&#105;&#108;&#116;&#111;&#58;&#114;&#101;&#97;&#108;&#119;&#111;&#114;&#108;&#100;&#64;&#114;&#119;&#115;&#99;&#114;&#105;&#112;&#116;&#115;&#46;&#99;&#111;&#109;'>&#114;&#101;&#97;&#108;&#119;&#111;&#114;&#108;&#100;&#64;&#114;&#119;&#115;&#99;&#114;&#105;&#112;&#116;&#115;&#46;&#99;&#111;&#109;</a>.
<table width='100%'  border='0' cellspacing='1' cellpadding='3'>
    <tr class='tableheader'>
      <td>Name</td>
      <td>Generate</td>
    </tr>

RWS;
//--END--//
		return $SHTML;
	}

	function licence_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
    <tr class='mainrow'>
      <td>{$data['name']}</td>
      <td>{$data['generate']}</td>
    </tr>

RWS;
//--END--//
		return $SHTML;
	}

	function licence_foot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
