<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_files.php

/*********************************************************
 * $HeadURL: http://www.maidenfans.com/svn/rwdownload_new/TRUNK/skins/skin1/skin_files.php $
 * $Revision: 50 $
 * $LastChangedBy: realworld $
 * $LastChangedDate: 2008-12-20 20:32:52 +0000 (Sat, 20 Dec 2008) $
 * Skin file auto generated by RW::Download v4.1.1
 * It is highly recommended you do NOT edit this file
 * Doing so could break the skinning engine and the script
 * This skin can be edited by using the Skin Controls in the Admin CP
 *********************************************************/
class skin_files
{
	function adreview_block($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>&gt; {$rwdInfo->lang['adminreview']}</div>
</div>
	<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
					<tr class='mainrow'>
						<td>{$data['adminreview']}</td>
					</tr>
				</table>
			</td>
          </tr>
  	</table>
</div>
RWS;
//--END--//
		return $SHTML;
	}

	function emailFriend($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
{$data['post']}
<div class='tableborder'>
	<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr class='tabletitle'>
            <td width='18'><img src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''></td>
            <td background='{$rwdInfo->skinurl}/images/headerbg.gif'><b>> {$rwdInfo->lang['emaillink']}</b></td>
            <td width='31'><img src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''></td>
          </tr>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
					<tr class='mainrow'>
						<td width='150'>
						{$rwdInfo->lang['yourname']}:
						</td>
						<td>
RWS;
//startif
		if ($data['username']) {
			$SHTML .= <<<RWS
{$data['username']}<input type='hidden' name='name' value='{$data['username']}'>
RWS;
		}//endif
		else {
			$SHTML .= <<<RWS
<input type='text' name='name' style='width:100%'>
RWS;
		}//endelse
		$SHTML .= <<<RWS
						</td>
					</tr>
					<tr class='mainrow'>
						<td>
						{$rwdInfo->lang['youremail']}:
						</td>
						<td>
						<input type='text' name='email' style='width:100%' value='{$data['email']}'>
						</td>
					</tr>
					<tr class='mainrow'>
						<td>
						{$rwdInfo->lang['friendsname']}:
						</td>
						<td>
						<input type='text' name='rname' style='width:100%'>
						</td>
					</tr>
					<tr class='mainrow'>
						<td>
						{$rwdInfo->lang['friendsemail']}:
						</td>
						<td>
						<input type='text' name='remail' style='width:100%'>
						</td>
					</tr>
RWS;
//startif
		if ($data['captcha']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['antispam']}: </td>
					<td valign='top'><img src='{$data['captcha']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['securitycode']}: <br>
					{$rwdInfo->lang['securitydesc']}</td>
					<td valign='top'><input name='regbot' type='text' size='30'></td>
				</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
                    <tr class='mainrow'>
                        <td>
                        {$rwdInfo->lang['message']}:
                        </td>
                        <td>
                        <textarea name='message' rows='5' cols='30' style='width:100%'></textarea>
                        </td>
                    </tr>
				</table>
			</td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><input type='hidden' name='captchaid' value='{$data['captchaid']}'>
            <input type='submit' name='send_email' value='{$rwdInfo->lang['submit']}'>
			<input type='reset' name='Submit2' value='{$rwdInfo->lang['reset']}'></td>
            <td>&nbsp;</td>
          </tr>
	  
  	</table>
</div></form>
RWS;
//--END--//
		return $SHTML;
	}

	function image_block($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<p>{$data['thumb']}</p>
RWS;
//--END--//
		return $SHTML;
	}

	function desc_block($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>&gt; {$rwdInfo->lang['description']}</div>
</div>
	<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
					<tr class='mainrow'>
						<td>
						{$data['description']}
						</td>
					</tr>
				</table>
			</td>
          </tr>
  	</table>
</div>
RWS;
//--END--//
		return $SHTML;
	}

	function mirrorrow($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
[ {$data['mirror']} ]&nbsp;
RWS;
//--END--//
		return $SHTML;
	}

	function cat_listing_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td>{$data['onethumb']}</td>
                  <td>{$data['name']} {$data['pinned']} {$data['new']} {$data['updated']}</td>
                  <td><div align='center'>{$data['author']}</div></td>
                  <td><div align='center'>{$data['date']}</div></td>
<td><div align='center'>{$data['filesize']}</div></td>                  
<td><div align='center'>{$data['downloads']}</div></td>
RWS;
//startif
		if ($data['editvalue']) {
			$SHTML .= <<<RWS
<td><div align='center'><input type='checkbox' name='dlid[]' value='{$data['editvalue']}'></div></td>
RWS;
		}//endif
		$SHTML .= <<<RWS
                </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function comment_block($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<p>{$data['comments']}<br></p>
RWS;
//--END--//
		return $SHTML;
	}

	function comment_foot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
			<tr><td>{$data['pages']}</td><td><div align='right'>{$data['mod_options']}</div></td></tr></table></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div>
RWS;
//--END--//
		return $SHTML;
	}

	function custom_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$data['caption']}</td>
					<td valign='top'>{$data['customdata']}</td>
				</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function comment_head($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
{$data['pages']}
	<div class='tableborder'>
	<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>&gt; {$rwdInfo->lang['comments']}</div>
</div>
	<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
RWS;
//--END--//
		return $SHTML;
	}

	function comment_form($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<form method='post' enctype='multipart/form-data' action='{$data['comment_post']}'>
	<div class='tableborder'>
	<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>> {$rwdInfo->lang['addcomment']}</div>
</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'>
				<table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
				<tr class='mainrow'>
	                  <td width='150'>{$rwdInfo->lang['username']}:</td>
					  <td>{$data['username']}</td>
				</tr>
RWS;
//startif
		if ($data['captcha']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['antispam']}: </td>
					<td valign='top'><img src='{$data['captcha']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['securitycode']}: <br>
					{$rwdInfo->lang['securitydesc']}</td>
					<td valign='top'><input name='regbot' type='text' size='30'></td>
				</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
				<tr class='mainrow'>
	                  <td width='150'>{$rwdInfo->lang['message']}:</td>
					  <td><textarea name='uc_message' rows='7' style='width:99%'>{$data['message']}</textarea></td>
				</tr>
			</td>
			</tr>
	</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><input type='hidden' name='captchaid' value='{$data['captchaid']}'>
            <input type='submit' name='add_comment' value='{$rwdInfo->lang['submit']}'>
			<input type='reset' name='Submit2' value='{$rwdInfo->lang['reset']}'></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
RWS;
//--END--//
		return $SHTML;
	}

	function report_form($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<form method='post' enctype='multipart/form-data' action='{$data['report_post']}'>
    <div class='tableborder'>
    <div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>> {$rwdInfo->lang['addcomment']}</div>
</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr class='mainrow'>
            <td colspan='3'>
                {$rwdInfo->lang['warn_report']}
                <table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
                <tr class='mainrow'>
                      <td width='150'>{$rwdInfo->lang['reason']}:</td>
                      <td><textarea rows='5' cols='50' name='reason'></textarea></td>
                </tr>
RWS;
//startif
		if ($data['captcha']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
                    <td valign='top'>{$rwdInfo->lang['antispam']}: </td>
                    <td valign='top'><img src='{$data['captcha']}'></td>
                </tr>
                <tr class='mainrow'>
                    <td valign='top'>{$rwdInfo->lang['securitycode']}: <br>
                    {$rwdInfo->lang['securitydesc']}</td>
                    <td valign='top'><input name='regbot' type='text' size='30'></td>
                </tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
                
            </td>
            </tr>
    </table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><input type='hidden' name='captchaid' value='{$data['captchaid']}'>
            <input type='submit' name='confirm' value='{$rwdInfo->lang['confirm']}'>
            <input type='submit' name='cancel' value='{$rwdInfo->lang['cancel']}'></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
RWS;
//--END--//
		return $SHTML;
	}

	function file_view_download($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<div align='right'>{$data['file_icon']} <a href='{$data['download_url']}' target='{$data['target']}'>{$rwdInfo->lang['download']}</a></div>
RWS;
//--END--//
		return $SHTML;
	}

	function empty_download($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['download']}:</td>
					<td valign='top'><input name='download' type='file' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dlurl']}:</td>
					<td valign='top'><input name='downloadurl' type='text' size='30' value='http://'></td>
				</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function comment_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='tableheader'>
                  <td width='150'><b>{$data['date']}</b></td>
				  <td><div align='right'>{$data['edit']} | {$data['delete']}</div></td>
			</tr>
			<tr class='mainrow'>
			<td>{$rwdInfo->lang['username']}:</td>
			   <td>{$data['user']}</td>
			 </tr>
			 <tr class='mainrow'> 
			<td valign='top'>{$rwdInfo->lang['comment']}:</td>
			   <td>{$data['comment']}</td>
			 </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function cat_listing_foot($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
			<tr><td>{$data['pages']}</td><td><div align='right'>{$data['mod_options']}</div></td></tr></table></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
<div class='tableborder'>
<table width='100%'  border='0' cellspacing='0' cellpadding='0' summary=''>
  <tr class='subfooter'>
    <td>{$data['order_boxes']}</td>
    <td>{$data['catSelect']}</td>
  </tr>
</table>
</div>
RWS;
//--END--//
		return $SHTML;
	}

	function cat_listing_head($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<form method='post' enctype='multipart/form-data' action='index.php?ACT=massmod'>
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>&gt; {$data['cat_name']}</div>
</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
                <tr class='tableheader'>
                  <td width='40'>&nbsp;</td>
                  <td>{$rwdInfo->lang['name']}</td>
                  <td><div align='center'>{$rwdInfo->lang['author']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['date']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['filesize']}</div></td>
                  <td><div align='center'>{$rwdInfo->lang['downloads']}</div></td>
RWS;
//startif
		if ($data['mod_options']) {
			$SHTML .= <<<RWS
<td><div align='center'>{$rwdInfo->lang['select']}</div></td>
RWS;
		}//endif
		$SHTML .= <<<RWS
                </tr>
RWS;
//--END--//
		return $SHTML;
	}

	function download_link($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['download']}:</td>
					<td valign='top'>{$data['dlinfo']}</td>
				</tr>
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['filetype']}:</td>
					<td valign='top'>{$data['typeinfo']}</td>
				</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function thumb_row($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dlthumb']}:</td>
					<td valign='top'><input name='{$data['thumbnum']}' type='file' width='30'></td>
				</tr>
RWS;
//--END--//
		return $SHTML;
	}

	function add_file($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
{$data['thumbtable']}
{$data['formpost']}
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>> {$data['title']}</div>
</div>
<table width='100%'  border='0 align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'>
			<table width='100%' border='0' cellspacing='1' cellpadding='3' summary=''>
				<tr class='mainrow'>
					<td valign='top' width='300'>{$rwdInfo->lang['dlname']}:</td>
					<td valign='top'><input style='width:99%' name='name' type='text' size='30' value='{$data['name']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['dldesc']}:</td>
					<td valign='top'><textarea style='width:99%' name='description' cols='24' rows='5'>{$data['description']}</textarea></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['author']}:</td>
					<td valign='top'><input style='width:99%' name='author' type='text' size='30' value='{$data['author']}'></td>
				</tr>
RWS;
//startif
		if ($data['usingFullVersion']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['thumblimit']}:</td>
					<td valign='top'><input name='thumbs' type='text' size='3' value='{$data['thumbs']}'> <input type='submit' name='updateform' value='{$rwdInfo->lang['updateform']}'></td>
				</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
				{$data['thumbrows']}
				{$data['downloadrows']}
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['mirror']}<br>{$rwdInfo->lang['fullurl']}</td>
					<td valign='top'>
						<table width='100%'  border='0 align='center' cellpadding='0' cellspacing='0' summary=''>
							<tr>
								<td>{$rwdInfo->lang['mirrorurl']}</td>
								<td>{$rwdInfo->lang['mirrorname']}</td>
							</tr><tr>
								<td><textarea style='width:99%' name='mirrorurls' cols='24' rows='5'>{$data['mirrors']}</textarea></td>
								<td><textarea style='width:99%' name='mirrornames' cols='24' rows='5'>{$data['mirrornames']}</textarea></td>
							</tr>
						</table>
					</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['version']} [{$rwdInfo->lang['optional']}]:</td>
					<td valign='top'><input style='width:99%' name='version' type='text' size='30' value='{$data['version']}'></td>
				</tr>
RWS;
//startif
		if ($data['usingFullVersion']) {
			$SHTML .= <<<RWS
{$data['customRows']}
RWS;
		}//endif
		$SHTML .= <<<RWS
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['cat']}:</td>
					<td valign='top'>{$data['catlistbox']}</td>
				</tr>
RWS;
//startif
		if ($data['usingFullVersion']) {
			$SHTML .= <<<RWS
{$data['adminrows']}
RWS;
		}//endif
//startif
		if ($data['captcha']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['antispam']}: </td>
					<td valign='top'><img src='{$data['captcha']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['securitycode']}: <br>
					{$rwdInfo->lang['securitydesc']}</td>
					<td valign='top'><input name='regbot' type='text' size='30'></td>
				</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
				<tr class='mainrow'>
				<td valign='top' colspan='2'><b><div align='center'>{$rwdInfo->lang['warn_upload']}</div></b></td>
				</tr>
			</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td>
            <input type='hidden' name='captchaid' value='{$data['captchaid']}'>
			<input type='hidden' name='did' value='{$data['id']}'>
<input type='hidden' name='oldfile' value='{$data['download']}'>			
<input type='hidden' name='owner' value='{$data['owner']}'>
{$data['oldcategory']}
<input type='hidden' name='filesize' value='{$data['filesize']}'>
<input type='hidden' name='realsize' value='{$data['realsize']}'>
<input type='hidden' name='images' value='{$data['thumbs']}'>
<input type='hidden' name='downloads' value='{$data['downloads']}'>
<input type='hidden' name='oldthumb' value='{$data['oldthumb']}'>
<div align='center'><input type='submit' name='preview' value='{$rwdInfo->lang['preview']}'>
<input type='reset' name='reset' value='{$rwdInfo->lang['reset']}'></div>
			</td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div></form>
RWS;
//--END--//
		return $SHTML;
	}

	function admin_rows($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['adpinned']}:</td>
					<td valign='top'><input type='checkbox' name='pinned' value='checked' {$data['pinned']}></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['adrating']}:</td>
					<td valign='top'>{$data['adrating']}</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['adreview']}:</td>
					<td valign='top'><textarea style='width:99%' name='adminreview' cols='24' rows='5'>{$data['adminreview']}</textarea></td>
				</tr>
				{$data['customRows']}
RWS;
//--END--//
		return $SHTML;
	}

	function file_view($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<div class='tableborder'>
<div id='banner'>
  <img id='leftcap' src='{$rwdInfo->skinurl}/images/headerleft.gif' width='18' height='29' alt=''>
  <img id='rightcap' src='{$rwdInfo->skinurl}/images/headerright.gif' width='31' height='29' alt=''>
  <div id='catname'>> {$data['name']}</div>
</div>
<table width='100%' border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3' summary=''>
                <tr class='tableheader'>
                  <td colspan='3'><div align='right'>
RWS;
//startif
		if ($data['report_link']) {
			$SHTML .= <<<RWS
{$data['report_link']}
	|
RWS;
		}//endif
		$SHTML .= <<<RWS
    {$data['email_link']} {$data['edit']} {$data['delete']}</div></td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['filesize']}:</td>
				  <td colspan='2'>{$data['filesize']}</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['author']}:</td>
				  <td colspan='2'>{$data['author']}</td>
                </tr>
RWS;
//startif
		if ($data['version']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['version']}:</td>
				  <td colspan='2'>{$data['version']}</td>
                </tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['downloads']}:</td>
				  <td colspan='2'>{$data['downloads']}</td>
                </tr>
				<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['views']}:</td>
				  <td colspan='2'>{$data['views']}</td>
                </tr>
RWS;
//startif
		if ($data['isFullVersion']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['rating']}:</td>
				  <td>{$data['adminrating']}</td>
				  <td>{$data['userrating']}
<if='{$data['votes']}'>
&nbsp; {$rwdInfo->lang['with']} {$data['votes']} {$rwdInfo->lang['votes']}
RWS;
		}//endif
		$SHTML .= <<<RWS
</td>
</if>
                </tr>
RWS;
//startif
		if ($data['mirrors']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
                  <td width='150'>{$rwdInfo->lang['mirrors']}:</td>
				  <td colspan='2'>{$data['mirrors']}</td>
                </tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
	</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0' summary=''>
			<tr><form method='post' enctype='multipart/form-data' action='{$data['add_rate']}' name='dlcomment'>
			<td width='33%'>
<select name='uc_rating' id='uc_rating'>
	<option value='1'>1</option>
	<option value='2'>2</option>
	<option value='3'>3</option>
	<option value='4'>4</option>
	<option value='5' selected>5</option>
	<option value='6'>6</option>
	<option value='7'>7</option>
	<option value='8'>8</option>
	<option value='9'>9</option>
	<option value='10'>10</option>
  </select> <input type='submit' name='rate_file' value='{$rwdInfo->lang['rate']}'></td></form>
  <td width='33%'><div align='center'>
RWS;
//startif
		if ($data['addcomment']) {
			$SHTML .= <<<RWS
{$data['addcomment']}
RWS;
		}//endif
		else {
			$SHTML .= <<<RWS
<!-- Put anything here that you want to appear when comments are not available (ie. logged out) -->
RWS;
		}//endelse
		$SHTML .= <<<RWS
</div></td>
  <td>
RWS;
//startif
		if ($data['download_link']) {
			$SHTML .= <<<RWS
{$data['download_link']}
RWS;
		}//endif
		else {
			$SHTML .= <<<RWS
<div align='right'>{$rwdInfo->lang['nodownload']}</div>
RWS;
		}//endelse
		$SHTML .= <<<RWS
</td></tr></table></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div>
{$data['description_block']}
{$data['adminreview_block']}
{$data['image_block']}
{$data['comments_block']}
RWS;
//--END--//
		return $SHTML;
	}
}

?>
