<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_login.php
// Skin file auto generated by RW::Download v4.0 Beta 3 [14/05/04]
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_login
{
	function login_form($data)
	{
		global $rwdInfo;
//--START--//
		$SHTML = <<<RWS
<form method='post' enctype='multipart/form-data' action='{$data['posturl']}' {$data['loginCallback']}>
<div class='tableborder'>
<div id="banner">
	  <img id="leftcap" src="{$rwdInfo->skinurl}/images/headerleft.gif" width="18" height="29">
	  <img id="rightcap" src="{$rwdInfo->skinurl}/images/headerright.gif" width="31" height="29">
	  <div id='catname'>&gt; {$rwdInfo->lang['login']}</div>
	</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3'>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['username']}: </td>
					<td valign='top'>
					<input type='text' name='username'>
					</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['password']}: </td>
					<td valign='top'>
					<input type='password' name='userpw'>
					</td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['stayloggedin']}: </td>
					<td valign='top'>
					<input type='checkbox' name='remember' value='1' checked>
					</td>
				</tr>
		</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><div align='center'>
			<input type='submit' name='login' value='{$rwdInfo->lang['login']}'>
			</div>
			<input type='hidden' name='referurl' value='{$data['referer']}'>
            <input type="hidden" name="hash_passwrd" value=""></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div>
</form>
RWS;
//--END--//
		return $SHTML;
	}

	function login_redirect($data)
	{
		global $rwdInfo;
//--START--//
		$SHTML = <<<RWS
<SCRIPT LANGUAGE='JavaScript'>
	<!--
	function redirect()
	{
		parent.location.href='{$data['referurl']}'
	}
	-->
	</SCRIPT>
	
	{$data['message']}
	<SCRIPT LANGUAGE='JavaScript'>
	<!--
			setTimeout('redirect()',1000)
	-->
	</SCRIPT>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
