<?php
/*
 * Copyright (c) 2023.
 * RW::Software
 * Dave Conley
 * https://www.rwscripts.com/
 */
// skin_register.php
// Skin file auto generated by RW::Download v4.0 RC1 [5/12/04]
// It is highly recommended you do NOT edit this file
// Doing so could break the skinning engine and the script
// This skin can be edited by using the Skin Controls in the Admin CP
class skin_register
{
	function register_form($data = NULL)
	{
		global $rwdInfo;
//--START--//
		$SHTML .= <<<RWS
<form method='post' enctype='multipart/form-data' action='{$data['posturl']}'>
<div class='tableborder'>
<div id="banner">
	  <img id="leftcap" src="{$rwdInfo->skinurl}/images/headerleft.gif" width="18" height="29">
	  <img id="rightcap" src="{$rwdInfo->skinurl}/images/headerright.gif" width="31" height="29">
	  <div id='catname'>&gt; {$rwdInfo->lang['register']}</div>
	</div>
<table width='100%'  border='0' align='center' cellpadding='0' cellspacing='0'>
          <tr>
            <td colspan='3'><table width='100%'  border='0' cellspacing='1' cellpadding='3'>
				<tr class='mainrow'>
					
					<td valign='top' width='150'>{$rwdInfo->lang['username']}: </td>
					<td valign='top'><input name='username' type='text' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['email']}: </td>
					<td valign='top'><input name='email' type='text' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['confirmemail']}: </td>
					<td valign='top'><input name='email2' type='text' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['password']}: </td>
					<td valign='top'><input name='password' type='password' size='30'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['confirmpassword']}: </td>
					<td valign='top'><input name='password2' type='password' size='30'></td>
				</tr>
RWS;
//startif
		if ($data['regbot']) {
			$SHTML .= <<<RWS
<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['antispam']}: </td>
					<td valign='top'><img src='{$data['regbot']}'></td>
				</tr>
				<tr class='mainrow'>
					<td valign='top'>{$rwdInfo->lang['securitycode']}: <br>
					{$rwdInfo->lang['securitydesc']}</td>
					<td valign='top'><input name='regbot' type='text' size='30'></td>
				</tr>
RWS;
		}//endif
		$SHTML .= <<<RWS
				
		</table></td>
          </tr>
          <tr class='tablefooter'>
            <td>&nbsp;</td>
            <td><input type='hidden' name='regid' value='{$data['regid']}'>
			<div align='center'><input type='submit' name='submit' value='{$rwdInfo->lang['submit']}'>
		  	<input type='reset' name='reset' value='{$rwdInfo->lang['reset']}'></div></td>
            <td>&nbsp;</td>
          </tr>
  </table>
</div>
</form>
RWS;
//--END--//
		return $SHTML;
	}
}

?>
